# Blog info
blog_name: Jiacy
slogan: 一个爱折腾的Dreamer，只会写hello world的Coder；懒惰的Sofaman，不服输的Fighter。这是主页，更是梦。
url: http://www.jiacy.top

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /earth_favicon.ico

# For seo
keywords: Jiacy,一个不务正业的大学生、不入流的代码民工、不靠谱的笔记本推荐者、即将失业的准就业青年

# Web footer
footer: © 2017 ❤ Jiacy  |  Power by Hexo. Built on Github Pages.

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
#  - name: Project
#    url: /project/
#    target_blank: false
  - name: Github
    url: https://github.com/jiacy061
    target_blank: true
  - name: About
    url: /about/
    target_blank: false
  - name: More
    url: http://www.jiacy.me
    target_blank: true #在新页面打开

# config page nav
page_nav:
  - name: 文章
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /categories/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 项目
    url: /project/
    target_blank: false
  - name: 链接
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
#  - name: RSS
#    url: /atom.xml
#    target_blank: true # 在新页面打开
#  - name: 搜索
#    url: /search/
#    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 文章摘要
article:
  isShow: true # true|false

# 盒子
toolbox:
  isShow: true # true|false
  text: 盒子

search_slogan:
  isShow: true # true|false
  text: Do you dream anything?

link_slogan:
  isShow: true # true|false
  text: 交换友情链接可以邮件 contact@jiacy.me


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 感谢大佬们的支持
  items:
    - type: 志愿帮只招人，不收费
      text: QQ扫一扫
      imgUrl: /images/QQ-QR.jpg
#    - type: 不差钱
#      text: 支付宝扫一扫
#      imgUrl: /images/qr-alipay.png

yundashang:
  isShow: true # 第三方云打赏 true|false
  id: dash-main-id-879895 # 第三方云打赏id，在云打赏的代码中可以找到




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service
# 新增来必力第三方评论板块，需要自行前往https://livere.com/注册帐号并绑定个人网站。
#disqus_shortname: Jiacy
#hypercomments_id: 89821
#gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc
livere:
  isShow: true # true | false , 必填项，空缺会出现问题
  uid: MTAyMC8zMTczMy84Mjk3 # uid可在来比力管理页面-代码管理中找到，是data-uid标签引号内的参数

# 注意，多说即将关闭，建议选用上面四个评论系统
#duoshuo_shortname: forsigner

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Seb,1996."
    - "不擅长编程，却热爱睡懒觉。"
    - "一个不务正业的大学生、不入流的代码民工、不靠谱的笔记本推荐者、即将失业的准就业青年。"
    - "擅长C/C++、Java、Go、Python、HTML等多种语言的hello world！"
    - "业内首席递茶员、某群认证学渣"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@jiacy061"
    text_value_url: https://github.com/jiacy061
#  - type: weibo
#    icon: icon-weibo
#    text_key: 微博
#    text_value: "@Too与子与兔"
#    text_value_url: http://weibo.com/2421552664
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "contact@jiacy.me"
    text_value_url: mailto:contact@jiacy.me
  - type: location
    icon: icon-location
    text_value: 重庆＆武汉
  - type: edu
    text_key: Education
    text_value: Wuhan University, Wuhan, the P.R.C
    text_value_url: http://www.whu.edu.cn/
  - type: line1
    text_key: 　
  - type: line2
    text_key: 　
  - type: copyright
    text_key: © 2017 ❤ Jiacy
  - type: power
    text_key: Power by Hexo | Theme - Fexo

link:
  - name: Jiacy的美帝服务器
    info: 科学上网，手动搭梯~
    url: http://www.jiacy.me/
    avatar: http://www.jiacy.me/img/favicon.png
  - name: YJ-Cyber
    info: 一个Polymath的博客
    url: https://www.yjcyber.com/
    avatar: https://www.yjcyber.com/icon/yjcyber.png


project:
  - type: personal
    name: QQ图片防撤回工具
    url: http://www.jiacy.me/downloads/QQ_ToolsToPreventTheWithdrawal.jar
    intro: 一款做工很烂的QQ和TIM仅限windows端的图片防撤回工具
  - type: personal
    name: 进制转换器
    url: http://www.jiacy.me/downloads/Conversion-System.apk
    intro: 一款做工很勉强的Android端的进制转换器
  - type: personal
    name: 时间累计记录软件
    url: http://www.jiacy.me/downloads/Time-Accumulator.apk
    intro: 一款做工更烂的Android端的时间累计记录软件，勉强用于记录宅图书馆的时间
